# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

variables:
  buildConfiguration: 'Release'

jobs:
- job: LinuxBuild
  displayName: 'Build for Linux'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sln'
      arguments: '--configuration $(buildConfiguration)'

  - task: MSBuild@1
    displayName: 'Build .sfproj files'
    inputs:
      solution: '**/*.sfproj'
      msbuildArchitecture: 'x64'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      msbuildArguments: '/t:Package /p:PackageLocation=$(build.artifactstagingdirectory)\applicationpackage'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)\pdbs'
    inputs:
      SourceFolder: '$(build.artifactstagingdirectory)\applicationpackage'
      Contents: '**\*.pdb'
      TargetFolder: '$(build.artifactstagingdirectory)\pdbs'

  - task: DeleteFiles@1
    displayName: 'Delete files from $(build.artifactstagingdirectory)\applicationpackage'
    inputs:
      SourceFolder: '$(build.artifactstagingdirectory)\applicationpackage'
      Contents: '**\*.pdb'
